name: synferm-predictions
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11.*
  - conda-forge::rdkit=2023.03.*
  - scikit-learn=1.3.*
  - conda-forge::py-xgboost=1.7.*
  - seaborn=0.12.*
  - pytorch::pytorch=2.0.*
  - pytorch::torchvision
  - pytorch::torchaudio
  - lightning=2.0.*
  - torchmetrics=1.0.*
  - dglteam::dgl
  - pre-commit=3.3.*
  - pip
  - pip:
    - dgllife
    - botorch
    - ax-platform
    - wandb
    - jupyter
    - git+https://github.com/bp-kelley/descriptastorus
